# Generated by Django 5.0 on 2024-01-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
