# Generated by Django 5.0 on 2024-01-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_alter_discounts_created_at_alter_discounts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='driver_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='vendor_name',
            field=models.CharField(max_length=150),
        ),
    ]
