# Generated by Django 4.2.5 on 2024-01-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_alter_discounts_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
    ]
