# Generated by Django 4.2.5 on 2024-01-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_discounts_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounts',
            name='city',
        ),
    ]
