# Generated by Django 4.2.5 on 2024-01-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_remove_discounts_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
