# Generated by Django 4.2.5 on 2024-01-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_alter_discounts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
