# Generated by Django 4.2.5 on 2024-01-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0008_alter_discounts_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discounts',
            new_name='visits',
        ),
    ]
