# Generated by Django 4.2.5 on 2024-01-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0010_rename_visits_discounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discounts',
            new_name='visits',
        ),
    ]
