# Generated by Django 4.2.5 on 2024-01-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0011_rename_discounts_visits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='visits',
            new_name='Discounts',
        ),
    ]
