# Generated by Django 4.2.5 on 2024-01-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0012_rename_visits_discounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_given',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
