# Generated by Django 4.2.5 on 2024-01-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0013_discount_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount_given',
            name='car',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='discount_given',
            name='car_color',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='discount_given',
            name='discount',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='discount_given',
            name='driver_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='discount_given',
            name='driver_phone',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='discount_given',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='discount_given',
            name='plate_number',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='discount_given',
            name='rating',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='discount_given',
            name='vendor_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='discount_given',
            name='vendor_phone',
            field=models.CharField(default='', max_length=150),
        ),
    ]
