# Generated by Django 5.0 on 2023-12-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('qr_code', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('lenk', models.CharField(max_length=150)),
            ],
        ),
    ]
