# Generated by Django 5.0 on 2023-12-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='lenk',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='offer',
            name='subtitle',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
