# Generated by Django 5.0 on 2023-12-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_posts_delete_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='typr',
            new_name='type',
        ),
    ]
