# Generated by Django 4.2.5 on 2024-02-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_typr_posts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('logo', 'Logo'), ('competition', 'Competition')], max_length=150),
        ),
    ]
