# Generated by Django 4.2.5 on 2024-02-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_posts_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('video', 'video'), ('logo', 'Logo'), ('competition', 'Competition')], max_length=150),
        ),
    ]
