# Generated by Django 4.2.5 on 2024-02-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_posts_link_alter_posts_subtitle_alter_posts_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='type',
            field=models.CharField(choices=[('video', 'video'), ('competition', 'Competition'), ('logo', 'Logo'), ('post', 'Post')], max_length=150),
        ),
    ]
