# Generated by Django 4.2.5 on 2024-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_posts_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='posts',
            name='type',
            field=models.CharField(choices=[('video', 'video'), ('logo', 'Logo'), ('competition', 'Competition'), ('post', 'Post')], max_length=150),
        ),
    ]
