# Generated by Django 4.2.5 on 2023-12-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Captin',
            new_name='Driver',
        ),
        migrations.RenameModel(
            old_name='Vender',
            new_name='Vendor',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vender',
            new_name='vendor',
        ),
    ]
