# Generated by Django 5.0 on 2023-12-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_captin_driver_rename_vender_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
