# Generated by Django 5.0 on 2023-12-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_vendor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(default='بغداد', max_length=20),
        ),
    ]
