# Generated by Django 5.0 on 2023-12-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vendor_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(default='بغداد', max_length=120),
        ),
    ]
