# Generated by Django 5.0 on 2024-01-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_driver_password_remove_vendor_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
    ]
