# Generated by Django 5.0 on 2024-01-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_driver_user_remove_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='password',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
