# Generated by Django 5.0 on 2024-01-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_driver_password_vendor_password_alter_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='qr_code',
            field=models.ImageField(upload_to='image'),
        ),
    ]
