# Generated by Django 5.0 on 2024-01-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_vendor_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='qr_code',
            field=models.ImageField(default='image/logo.jpg', upload_to='image'),
        ),
    ]
