# Generated by Django 5.0 on 2024-01-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_vendor_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
