# Generated by Django 4.2.5 on 2024-01-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_lenk_vendor_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Sub_Category',
            field=models.CharField(default='', max_length=120),
        ),
    ]
