# Generated by Django 4.2.5 on 2024-01-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_vendor_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='Main_Category',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='driver',
            name='qr_code',
            field=models.ImageField(default='image/logo.jpg', upload_to='image'),
        ),
    ]
