# Generated by Django 4.2.5 on 2024-01-26 21:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_vendor_main_category_remove_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user_id',
            field=models.CharField(default=users.models.generate_random_id, max_length=15, unique=True),
        ),
    ]
