# Generated by Django 4.2.5 on 2024-01-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='city',
            field=models.CharField(default='بغداد', max_length=120),
        ),
        migrations.AddField(
            model_name='offer',
            name='link',
            field=models.CharField(default='بغداد', max_length=150),
        ),
        migrations.AddField(
            model_name='offer',
            name='phone_number',
            field=models.CharField(default='بغداد', max_length=13),
        ),
    ]
