# Generated by Django 4.2.5 on 2024-01-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_offer_city_remove_offer_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='Platinum',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Silver',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='golden',
            field=models.TextField(default='', null=True),
        ),
    ]
