# Generated by Django 4.2.5 on 2024-01-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_offer_platinum_alter_offer_silver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='Platinum',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Silver',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='golden',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
