# Generated by Django 4.2.5 on 2024-01-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_offer_platinum_alter_offer_silver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
