# Generated by Django 4.2.5 on 2024-01-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_delete_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='qr_code',
        ),
    ]
