# Generated by Django 4.2.5 on 2024-02-20 10:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_driver_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='user_id',
            field=models.CharField(default=users.models.generate_random_id_vendor, max_length=5, unique=True),
        ),
    ]
